server:
  port: 9191
  
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_flinko?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        format-sql: true
#        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      
#      
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
##      username: test
##      password: test
#      database: db_flinko
      
      
 
  jackson:
    mapper:
      default-view-inclusion: true
    serialization:
      write-date-keys-as-timestamps: false  

  mvc:
    throw-exception-if-no-handler-found: true
    
    
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: projectmailer2021@gmail.com
    password: gxdamxbjednlmprd
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

sms:
  api-key: v9KCWaYPOVuxBslNjzZi5q4L1eJEX8kd3Ffm0TDSrUb26QIHgpuIkm8rZHwXtTpCyqRDMiN0dcUs2LVB
  send-id: FTWSMS
  language: english
  route: v3

#Should change to our credentials  
amazonProperties:
   endpointUrl: https://s3.ap-south-1.amazonaws.com
   accessKey: AKIAQNSTOCFO5AR2V2UX
   secretKey: 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
   bucketName: hrms-s3bucket
   region: ap-south-1
      
#file

      
#  upload:
#    location: C:\Users\User\Documents\Harbinger\image
      
